In [8]:
import numpy as np # import numpy liblary

In [9]:
li=[1,2,3,4]
arr=np.array(li)
arr


array([1, 2, 3, 4])

In [14]:
arr.shape

(4,)

In [15]:
type(arr)

numpy.ndarray

In [16]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,5,6,7]

In [17]:
arr1=np.array([l1,l2,l3])

In [18]:
arr1.shape

(3, 5)

In [19]:
#indexing
arr[3]

4

In [20]:
arr1[0][3]

4

In [21]:
arr[1:3]

array([2, 3])

In [22]:
arr[-1]

4

In [23]:
arr[:-1]

array([1, 2, 3])

In [24]:
arr

array([1, 2, 3, 4])

In [12]:
arr[::-2]

array([4, 2])

In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [26]:
arr1[:,1]

array([2, 3, 4])

In [27]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])