In [5]:
import numpy as np


In [6]:
np.nan

nan

In [7]:
li=[1,2,3,4]

In [9]:
x=np.array(li)
x

array([1, 2, 3, 4])

In [10]:
import pandas as pd
import numpy as np

In [13]:
data1=np.array([1,None,2,3])
data1

array([1, None, 2, 3], dtype=object)

In [15]:
%timeit np.arange(1E6 , dtype = int).sum()

3.38 ms ± 63.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
%timeit np.arange(1E6 , dtype = object).sum()

121 ms ± 5.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
data1.sum()
data1

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [25]:
data2= np.array([1,np.nan,3,4])

In [26]:
data2

array([ 1., nan,  3.,  4.])

In [27]:
pd.Series([1,np.nan,2,None])  # agar nan hai to bydefault datatype float hoyega

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [28]:
1 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [30]:
x=pd.Series(range(2),dtype=int)
x

0    0
1    1
dtype: int32

In [32]:
y = pd.Series(range(5), dtype=object)
y

0    0
1    1
2    2
3    3
4    4
dtype: object

In [34]:
y[0]=None
y

0    None
1       1
2       2
3       3
4       4
dtype: object

In [62]:
z= pd.Series(['hi',4,None,np.NaN], dtype=bool)
type(z[2])

numpy.bool_

In [37]:
pd.Series([1,np.nan,2,None,pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [40]:
pd.Series([1,np.nan,2,None,pd.NA])

0       1
1     NaN
2       2
3    None
4    <NA>
dtype: object

In [41]:
data=pd.Series([1,np.nan,'hello',None])
data.dropna()

0        1
2    hello
dtype: object

In [43]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object

In [44]:
import pandas as pd


In [50]:
df=pd.read_csv("C:\\Users\\navne\\Downloads\\anacondapy\\netflix_data.csv")
df

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4   
1             Mexico   December 23, 2016          2016        93   
2          Singapore   December 20, 2018          2011        78   
3      United States   November 16, 2017          2009        80   
4      United States     January 1, 2020          2008       123   
...              ...                 ...           ...       ...   
7782          Sweden    October 19, 2020          2005        99   
7783           India       March 2, 2019          2015       111   
7784             NaN  September 25, 2020          2019        44   
7785       Australia    October 31, 2020          2019         1   
7786  United Kingdom       March 1, 2020          2019        90   

                                            description             genre  
0     In a future where the elite inhabit an island ...  International TV  
1     After a devastating earthquake hits Mexico Cit...            Dramas  
2     When an army recruit is found dead, his fellow...     Horror Movies  
3     In a postapocalyptic world, rag-doll robots hi...            Action  
4     A brilliant group of students become card-coun...            Dramas  
...                                                 ...               ...  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries  

[7787 rows x 11 columns]

In [53]:
df.describe()

release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64 
 8   duration      7787 non-null   int64 
 9   description   7787 non-null   object
 10  genre         7787 non-null   object
dtypes: int64(2), object(9)
memory usage: 669.3+ KB


In [55]:
df.director.isnull()

0        True
1       False
2       False
3       False
4       False
        ...  
7782    False
7783    False
7784     True
7785     True
7786    False
Name: director, Length: 7787, dtype: bool

In [56]:
df.director.isnull().sum()

2389

In [57]:
df.director.fillna(0)

0                       0
1       Jorge Michel Grau
2            Gilbert Chan
3             Shane Acker
4          Robert Luketic
              ...        
7782          Josef Fares
7783          Mozez Singh
7784                    0
7785                    0
7786             Sam Dunn
Name: director, Length: 7787, dtype: object

In [61]:
df=pd.read_csv('netflix_data.csv')
df

show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4   
1             Mexico   December 23, 2016          2016        93   
2          Singapore   December 20, 2018          2011        78   
3      United States   November 16, 2017          2009        80   
4      United States     January 1, 2020          2008       123   
...              ...                 ...           ...       ...   
7782          Sweden    October 19, 2020          2005        99   
7783           India       March 2, 2019          2015       111   
7784             NaN  September 25, 2020          2019        44   
7785       Australia    October 31, 2020          2019         1   
7786  United Kingdom       March 1, 2020          2019        90   

                                            description             genre  
0     In a future where the elite inhabit an island ...  International TV  
1     After a devastating earthquake hits Mexico Cit...            Dramas  
2     When an army recruit is found dead, his fellow...     Horror Movies  
3     In a postapocalyptic world, rag-doll robots hi...            Action  
4     A brilliant group of students become card-coun...            Dramas  
...                                                 ...               ...  
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas  
7783  A scrappy but poor boy worms his way into a ty...            Dramas  
7784  In this documentary, South African rapper Nast...     Documentaries  
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV  
7786  This documentary delves into the mystique behi...     Documentaries  

[7787 rows x 11 columns]