In [2]:
import numpy as np


In [4]:
lst=[1,2,3,4]
arr=np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [11]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape

(3, 5)

In [17]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,5,6,7]
arr2=np.array([[l1,l2,l3]])

In [18]:
arr2.shape

(1, 3, 5)

In [19]:
arr

array([1, 2, 3, 4])

In [20]:
arr[0]

1

In [21]:
arr[::-1]

array([4, 3, 2, 1])

In [22]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [30]:
arr1[1:,3:5]

array([[5, 6],
       [6, 7]])

In [36]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [37]:
arr1[:2,2:4]

array([[3, 4],
       [4, 5]])

In [42]:
arr1



array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [56]:
arr1[:,3:5].shape

(3, 2)

In [57]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [67]:
arr1[0:,0:5:4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [94]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [99]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [102]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.zeros_like((4,2))

array([0, 0])

In [187]:
np.random.randint((10,50,5))

array([ 3, 12,  4])

In [191]:
np.random.randn(4,5)

array([[ 0.7021362 ,  1.16361726,  0.09736235,  0.0556172 ,  0.93882601],
       [-1.63850817, -0.52905737, -0.54045379,  2.48297249,  0.23817907],
       [ 0.83446672, -0.5117839 ,  1.2254833 ,  0.80996579, -0.69591109],
       [ 1.25638167, -0.73604035,  0.06793333, -0.31453068,  1.23531097]])

In [193]:
np.random.random_sample((4,4))

array([[0.97858121, 0.87043763, 0.79739034, 0.67135674],
       [0.15021429, 0.1128842 , 0.35960883, 0.71304977],
       [0.19383303, 0.74052035, 0.62977271, 0.80155417],
       [0.32722809, 0.86156355, 0.10886248, 0.68513048]])

In [195]:
import pandas as pd

In [197]:
d1=np.arange(0,20).reshape(5,4)

In [199]:
df=pd.DataFrame(data=d1,
             index=['row1','row2','row3','row4','row5'],
             columns=['column1','column2','column3','column4']
            
            )

In [200]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [201]:
df.tail()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [202]:
df.head(2)

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [203]:
df.tail(2)

column1  column2  column3  column4
row4       12       13       14       15
row5       16       17       18       19

In [204]:
type(df)

pandas.core.frame.DataFrame

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [211]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [212]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [216]:
type(df['column1'])

pandas.core.series.Series

In [215]:
df[['column1','column2','column3']]

pandas.core.frame.DataFrame

In [217]:
df.loc['row4']

column1    12
column2    13
column3    14
column4    15
Name: row4, dtype: int32

In [227]:
type(df.loc['row4'])

pandas.core.series.Series

In [224]:
df.loc[['row3','row4']]

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15

In [228]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [233]:
df.iloc[3:5,2:4]

column3  column4
row4       14       15
row5       18       19

In [235]:
df.iloc[0:5,::3]

column1  column4
row1        0        3
row2        4        7
row3        8       11
row4       12       15
row5       16       19

In [238]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [246]:
df= pd.DataFrame(data =[[1,np.nan,3],[2,3,4]],index=['row1','row2'],columns=['column1','column2','column3'])
df

column1  column2  column3
row1        1      NaN        3
row2        2      3.0        4

In [247]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [250]:
df[~df.isnull()]

column1  column2  column3
row1        1      NaN        3
row2        2      3.0        4

In [252]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [254]:
df['column3'].value_counts()

column3
3    1
4    1
Name: count, dtype: int64

In [256]:
df['column3'].unique()

array([3, 4], dtype=int64)

In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('vgsalesGlobale.csv')
df



Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [6]:
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [7]:
type(df)

pandas.core.frame.DataFrame